<?php

/**
 * Protect admin with login
 * The path is dynamically generated by env variable
 */
Route::group(['prefix' => getenv('ADMIN_BASE_PATH'), 'middleware' => ['auth.basic','auth.isadmin']], function () {

    /**
     * The admin Dashboard
     */
    Route::get('/', [
      'as' => 'adcp.dashboard',
      function () {
          return view('adcp.dashboard')->with('payments', App\Payment::orderBy('id', 'desc')->paginate(25));
      }
    ]);

    /**
     * Resources for payments / users
     */
    Route::resource('payments', 'AdminPaymentsController');
    Route::resource('users', 'UserController');

});
